### ISSUE TITLE
Assertion failed: class_decl && "TemplateSpecializationType is not a TplSpecDecl?"

### ISSUE THREAD

**Issue by vsapsai** [include-what-you-use/include-what-you-use#150]
Originally reported on Google Code with ID 150

```
I'm trying to use iwyu with http://github.com/mapbox/mapbox-gl-native on OS X 10.9.
I compiled iwyu against a clang 3.4.2 final stable.

I'm running this command:

CXX="include-what-you-use -Xiwyu --verbose=3 -isystem\"`xcode-select -p`/Toolchains/XcodeDefault.xctoolchain/usr/lib/c++/v1\""
make linux

and the first command gyp generates is

  include-what-you-use -Xiwyu --verbose=3 -isystem"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/c++/v1"
'-DNDEBUG' -I../../include -I../Release/obj/gen/include  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
-fasm-blocks -mpascal-strings -O3 -mmacosx-version-min=10.9 -arch x86_64 -std=c++11
-stdlib=libc++ -fvisibility-inlines-hidden -Wall -Wextra -I/usr/local/Cellar/libpng/1.6.10/include/libpng16
-I/usr/local/include -I/Users/kkaefer/Code/gl/native/mapnik-packaging/osx/out/build-cpp11-libcpp-universal/include
-MMD -MF ../Release/.deps/../Release/obj.target/llmr-x86/src/clipper/clipper.o.d.raw
 -c -o ../Release/obj.target/llmr-x86/src/clipper/clipper.o ../../src/clipper/clipper.cpp

which fails with

/Users/kkaefer/Code/include-what-you-use/iwyu.cc:3081: Assertion failed: class_decl
&& "TemplateSpecializationType is not a TplSpecDecl?"
make[1]: *** [../Release/obj.target/llmr-x86/src/clipper/clipper.o] Abort trap: 6

```

Reported by `mail@kkaefer.com` on 2014-06-17 14:38:03

**Comment by kimgr** [comment]
Let's close this, we haven't heard back for a year and a half.

**Comment by vsapsai** [comment]
Agree. As always, if somebody thinks the issue is not resolved, please reopen the issue.

**Comment by atopilski** [comment]
Hi can you reopent this issue, i have the same assertion on debian, iwyu installed  via apt-get.
```
Error running '/usr/bin/include-what-you-use': /tmp/buildd/iwyu-3.4/iwyu.cc:3081: Assertion failed: class_decl && "TemplateSpecializationType is not a TplSpecDecl?"
Child aborted
```

**Comment by kimgr** [comment]
Can you reduce a minimal test case we can try on the latest master? iwyu-3.4 sounds old, but I can't tell if it's before or after the proposed fix.

**Comment by elricbk** [comment]
Is there any way to make `iwyu` log file where it breaks?
I have the same issue with 0.8 version, but project where I have it is rather big so getting minimal example is non-trivial.

**Comment by kimgr** [comment]
Have you cranked up the verbosity level? `-Xiwyu -v7` usually gives more details than anyone can handle. Not sure if it makes it easier to locate the triggering construct for an assertion, but it's the best I can think of.

**Comment by chri7325** [comment]
I also seem to be hitting this a lot
```
src/json_exception.cpp:86:1 <Spelling=include/common/json_exception.h:135:9>: (6) [ BuiltinTypeLoc ] /home/chri7325/runtime/3rdparty/tools/llvm/bin/../include/c++/v1/__tuple:289:38: (53 in tpl) [ TemplateArgumentLoc ] 0x7fff73b50df0 char
Adding to processed_overload_locs: <class std::__1::allocator<class Esri_runtimecore::Common::JSON_object> &>
src/json_exception.cpp:86:1 <Spelling=include/common/json_exception.h:136:3>: (4) [ CompoundStmt ] /home/chri7325/runtime/3rdparty/tools/llvm/bin/../include/c++/v1/__tuple:289:38: (54 in tpl, fwd decl) [ SubstTemplateTypeParmType ] 0x7771088 0x8fb1da0 CompoundStmt class std::__1::allocator<class Esri_runtimecore::Common::JSON_object> &/home/chri7325/runtime/3rdparty/tools/llvm/bin/../include/c++/v1/vector:2955:28 <Spelling=/home/chri7325/runtime/3rdparty/tools/llvm/bin/../include/c++/v1/__config:441:15>0x7771088

 <include/common/json_exception.h:136:3, line/home/chri7325/runtime/3rdparty/tools/llvm/bin/../include/c++/v1/__tuple:289:38: (54 in tpl, fwd decl) [ SubstTemplateTypeParmTypeLoc ] :138:class std::__1::allocator<class Esri_runtimecore::Common::JSON_object> &3
>
`-ReturnStmt 0x7771070 </home/chri7325/runtime/3rdparty/tools/llvm/bin/../include/c++/v1/__tuple:289:38: (55 in tpl, fwd decl) [ LValueReferenceType ] line:0x8e74370 137:5class std::__1::allocator<class Esri_runtimecore::Common::JSON_object> &, 
<scratch space>:/home/chri7325/runtime/3rdparty/tools/llvm/bin/../include/c++/v1/__tuple:289:38: (56 in tpl, fwd decl) [ RecordType ] 20x8e1c3e0 :1>class std::__1::allocator<class Esri_runtimecore::Common::JSON_object>

  `-ImplicitCastExpr 0x7771058 <col:1> 'const char *' <ArrayToPointerDecay>
    `-StringLiteral 0x7771000 <col:1> 'const char [43]' lvalue "\"invalid star/home/chri7325/llvm-project/clang/tools/include-what-you-use/iwyu.cct of jso:n - expecting { o3282r: Assertion failed:  [class_decl && "TemplateSpecializationType is not a TplSpecDecl?"\""
```
iwyu was built using https://github.com/Esri/llvm-project-20170507/tree/runtimecore which has the clang_50 branch of IWYU.  This is happening on our linux builds.

**Comment by kimgr** [comment]
Thanks, reopening this, to see if we can figure out what's going on.

**Comment by kimgr** [comment]
@chri7325 I tried to reproduce this now, but it's hard since I don't know what code you're building.

Do you think you could describe a repeatable sequence from scratch to provoke this error? Thanks!

**Comment by kimgr** [comment]
See also #150 and #346

**Comment by chri7325** [comment]
@kimgr I'll try to see if I can get a small repro case going.  We're on the final stages of fully iwyuing our entire codebase and I think we have one more crash that we want to investigate but otherwise, things are going smoothly.  Once we finish everything up, I'll see if I can debug or get some reproducers for you.  If we can find any fixes, I'll try to get a PR up as well.

**Comment by Bu11etmagnet** [comment]
> We're on the final stages of fully iwyuing

This is it. iwyu has made it to the same level as Google: it has become a verb :)

Congratulations! :1st_place_medal:

**Comment by chri7325** [comment]
iwyuifying is another action verb we use around here

**Comment by chri7325** [comment]
@kimgr apologies for taking so long on a repro-case.  It took me some time to track down why the check was failing and then trying to come up with a repro case that didn't include our IP.  I was finally able to find a good repro case.  It looks like the check is being tripped when using std::get on std::tuple.  The example on cppreference was enough for me to reproduce this issue http://en.cppreference.com/w/cpp/utility/tuple/get

**Comment by kimgr** [comment]
Thanks! Do note, though, that std types make terrible repros because there are so many std library implementations :)

I'll try it when I get a chance and see if it triggers something on my gcc 7.2 system, and maybe reduce something from there.

Thank you so much for doing the legwork!

**Comment by jru** [comment]
Just gave it a try with a freshly installed gcc 7.3.0 on my ubuntu xenial env and could not make it trip.
I double-checked the std includes come from `/usr/lib/gcc/x86_64-linux-gnu/7.3.0/`

This is the example I used, to be on the same page:
```cpp
#include <iostream>
#include <string>
#include <tuple>

int main()
{
    auto t = std::make_tuple(1, "Foo", 3.14);
    // index-based access
    std::cout << "(" << std::get<0>(t) << ", " << std::get<1>(t)
              << ", " << std::get<2>(t) << ")\n";
    // type-based access
    std::cout << "(" << std::get<int>(t) << ", " << std::get<const char*>(t)
              << ", " << std::get<double>(t) << ")\n";
    // Note: std::tie and structured binding may also be used to decompose a tuple
}
```

**Comment by jru** [comment]
That's a lot to take in :) 

I have an idea. Can you run this below and copy the output?
```
include-what-you-use -v
```
It should tell us what kind of std library and version IWYU (clang) is using.

**Comment by elricbk** [comment]
If the problem is on the parsing stage won't it be enough to run a
preprocessor on the problematic file? Then you got full file (while really
huge) to reproduce the problem.

чт, 24 Май 2018, 9:08 J.Ru <notifications@github.com>:

**Comment by kimgr** [comment]
@elricbk It could work, but it's not guaranteed. IWYU analyzes both the ast and the physical structure (includes and relationships between them), so it might take a different path in the depending on include structure. 

That might not be the case here, though, is worth a try.

**Comment by chri7325** [comment]
Thanks for the suggestions and sorry for the repro work haha.  I was hoping the instructions would at least shine a light on whether building clang with std types was the issue.  Here's the output of include-what-you-use -v
```
clang version 5.0.0 
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/chri7325/runtime/3rdparty/tools/llvm/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.0.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
error: unable to handle compilation, expected exactly one compiler job in ''
```
I was able to get a bit more information with this but there's unfortunately some backstory.  So as I mentioned above, we need to build clang ourselves against the std runtime in order to support exceptions on Qt.  We're currently using clang 3.9 as our compiler and have include files for it at /usr/bin/include/v1.  When we build iwyu, we build it against the clang 5.0 branch so I think iwyu is using clang 5.0 headers as well as 3.9 headers.  If I run iwyu on the repro case, it builds fine until I add -stdlib=libc++, at which point, the parsing of the preprocessed source fails.  I wasn't able to use IWYU to create the preprocessed source since it crashes so I used clang 3.9 to do so.
[repro.txt](https://github.com/include-what-you-use/include-what-you-use/files/2036789/repro.txt)

**Comment by kimgr** [comment]
I ran IWYU on your preprocessed source and it segfaulted after running silent for a while. I don't think it's worth trying to work that out, since that's not an intended run-mode for IWYU. Still interested in a smaller repro :)

**Comment by eduardo-elizondo** [comment]
While this is not ideal, it got me through what I needed:

In iwyu.cc:3311:
```
// Temporary hack
// CHECK_(class_decl && "TemplateSpecializationType is not a TplSpecDecl?");
if (!class_decl) {
  return false;
}
```

Looking forward to a good fix.

**Comment by jru** [comment]
@Izzeri Thanks for the amazing repro! I just submitted a PR to fix this.

**Comment by fabledpig** [comment]
Hi!

I think this issue is still not fixed.

On branch clang_7.0, given the following test case:
```
class Foo {
};

using type = __type_pack_element<0, Foo>;

int main()
{
  return 0;
}
```

I get `TemplateSpecializationType has no decl of type TemplateDecl?`.

Backtrace:
```
#0  include_what_you_use::InstantiatedTemplateVisitor::TraverseDataAndTypeMembersOfClassHelper (this=0x555555944ed0, type=0x5555559bd280) at /home/levente.lenart/Projects/iwyu/include-what-you-use/iwyu.cc:3356
#1  0x000055555557aa14 in include_what_you_use::InstantiatedTemplateVisitor::TraverseTemplateSpecializationTypeHelper (this=0x555555944ed0, type=0x5555559bd280) at /home/levente.lenart/Projects/iwyu/include-what-you-use/iwyu.cc:3002
#2  0x000055555557aa8e in include_what_you_use::InstantiatedTemplateVisitor::TraverseTemplateSpecializationType (this=0x555555944ed0, type=0x5555559bd280) at /home/levente.lenart/Projects/iwyu/include-what-you-use/iwyu.cc:3008
#3  0x000055555557a226 in include_what_you_use::InstantiatedTemplateVisitor::ScanInstantiatedType (this=0x555555944ed0, caller_ast_node=0x7fffffffda60, resugar_map=...) at /home/levente.lenart/Projects/iwyu/include-what-you-use/iwyu.cc:2842
#4  0x000055555557e11d in include_what_you_use::IwyuAstConsumer::VisitTemplateSpecializationType (this=0x555555944ea0, type=0x5555559bd280) at /home/levente.lenart/Projects/iwyu/include-what-you-use/iwyu.cc:3947
#5  0x000055555564e09b in clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::WalkUpFromTemplateSpecializationType (this=0x555555944eb0, T=0x5555559bd280) at /usr/lib/llvm/7/include/clang/AST/TypeNodes.def:100
#6  0x000055555562d222 in clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseTemplateSpecializationTypeLoc (this=0x555555944eb0, TL=...) at /usr/lib/llvm/7/include/clang/AST/RecursiveASTVisitor.h:1306
#7  0x00005555555d0712 in clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseTypeLoc (this=0x555555944eb0, TL=...) at /usr/lib/llvm/7/include/clang/AST/TypeNodes.def:100
#8  0x000055555559d4a0 in include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseTypeLoc (this=0x555555944eb0, typeloc=...) at /home/levente.lenart/Projects/iwyu/include-what-you-use/iwyu.cc:374
#9  0x00005555555c90d9 in clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseTypeAliasDecl (this=0x555555944eb0, D=0x5555559bd370) at /usr/lib/llvm/7/include/clang/AST/RecursiveASTVisitor.h:1766
#10 0x000055555559b969 in clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseDecl (this=0x555555944eb0, D=0x5555559bd370) at /usr/lib/llvm/7/include/clang/AST/DeclNodes.inc:297
#11 0x0000555555589c83 in include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseDecl (this=0x555555944eb0, decl=0x5555559bd370) at /home/levente.lenart/Projects/iwyu/include-what-you-use/iwyu.cc:331
#12 0x000055555559d5e9 in clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseDeclContextHelper (this=0x555555944eb0, DC=0x555555961118) at /usr/lib/llvm/7/include/clang/AST/RecursiveASTVisitor.h:1388
#13 0x00005555555cc423 in clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseTranslationUnitDecl (this=0x555555944eb0, D=0x5555559610f8) at /usr/lib/llvm/7/include/clang/AST/RecursiveASTVisitor.h:1480
#14 0x000055555559c0b8 in clang::RecursiveASTVisitor<include_what_you_use::IwyuAstConsumer>::TraverseDecl (this=0x555555944eb0, D=0x5555559610f8) at /usr/lib/llvm/7/include/clang/AST/DeclNodes.inc:553
#15 0x0000555555589c83 in include_what_you_use::BaseAstVisitor<include_what_you_use::IwyuAstConsumer>::TraverseDecl (this=0x555555944eb0, decl=0x5555559610f8) at /home/levente.lenart/Projects/iwyu/include-what-you-use/iwyu.cc:331
#16 0x000055555557cad5 in include_what_you_use::IwyuAstConsumer::HandleTranslationUnit (this=0x555555944ea0, context=...) at /home/levente.lenart/Projects/iwyu/include-what-you-use/iwyu.cc:3596
#17 0x00007ffff5ca7e77 in clang::ParseAST(clang::Sema&, bool, bool) () from /usr/lib/llvm/7/bin/../lib64/../lib64/libclangParse.so.7.1
#18 0x00007ffff6adaf86 in clang::FrontendAction::Execute() () from /usr/lib/llvm/7/bin/../lib64/libclangFrontend.so.7.1
#19 0x00007ffff6a97832 in clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) () from /usr/lib/llvm/7/bin/../lib64/libclangFrontend.so.7.1
#20 0x000055555557e7b3 in main (argc=7, argv=0x7fffffffe108) at /home/levente.lenart/Projects/iwyu/include-what-you-use/iwyu.cc:4060
```

Please consider reopening this issue.

**Comment by fabledpig** [comment]
I opened a new issue (#698) and will submit a PR with a fix.
