### ISSUE TITLE
Test failure on Void Linux

### ISSUE THREAD

**Issue by meator** [include-what-you-use/include-what-you-use#1564]
Hey, I was trying to build include-what-you-use version 0.22 but couldn't get pas the following test failure:

```
...
192/205 Test #192: driver.test_exitcode_warn_error_always_arg ........   Passed    0.19 sec
        Start 193: driver.test_exitcode_warn_error_and_always
193/205 Test #193: driver.test_exitcode_warn_error_and_always ........   Passed    0.20 sec
        Start 194: driver.test_exitcode_warn_error_arg
194/205 Test #194: driver.test_exitcode_warn_error_arg ...............   Passed    0.20 sec
        Start 195: driver.test_generate_pch
195/205 Test #195: driver.test_generate_pch ..........................   Passed    0.17 sec
        Start 196: driver.test_multiple_inputs
196/205 Test #196: driver.test_multiple_inputs .......................   Passed    0.18 sec
        Start 197: driver.test_offload_apple
197/205 Test #197: driver.test_offload_apple .........................   Passed    0.20 sec
        Start 198: driver.test_offload_openmp
198/205 Test #198: driver.test_offload_openmp ........................***Failed    0.24 sec
INFO:root:Testing iwyu on tests/driver/offload_openmp.c
>>> Running /builddir/include-what-you-use-0.22/build/bin/include-what-you-use -Xiwyu --verbose=3 -fopenmp -fopenmp-targets=nvptx64 -nocudalib tests/driver/offload_openmp.c
error: cannot determine nvptx64 architecture: No NVIDIA GPU detected in the system; consider passing it via '-march'
warning: ignoring offload job for device toolchain: openmp

(tests/driver/offload_openmp.c has correct #includes/fwd-decls)

Traceback (most recent call last):
  File "/builddir/include-what-you-use-0.22/run_iwyu_tests.py", line 161, in <module>
    exit(RunTestFile(runner_args.run_test_file))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/include-what-you-use-0.22/run_iwyu_tests.py", line 127, in RunTestFile
    TestIwyuOnRelevantFiles(cc_file)
  File "/builddir/include-what-you-use-0.22/run_iwyu_tests.py", line 64, in TestIwyuOnRelevantFiles
    iwyu_test_util.TestIwyuOnRelativeFile(filename, files_to_check, verbose=True)
  File "/builddir/include-what-you-use-0.22/iwyu_test_util.py", line 688, in TestIwyuOnRelativeFile
    raise AssertionError(''.join(failures))
AssertionError:
Unexpected diagnostic:
cannot determine nvptx64 architecture: No NVIDIA GPU detected in the system; consider passing it via '-march'

Unmatched regex:
Executable ".*" doesn't exist!; consider passing it via '-march'


        Start 199: driver.test_preprocess_gcc
199/205 Test #199: driver.test_preprocess_gcc ........................   Passed    0.18 sec
        Start 200: driver.test_preprocess_msvc
200/205 Test #200: driver.test_preprocess_msvc .......................   Passed    0.18 sec
        Start 201: driver.test_save_temps
201/205 Test #201: driver.test_save_temps ............................   Passed    0.17 sec
        Start 202: driver.test_use_pch
202/205 Test #202: driver.test_use_pch ...............................   Passed    0.17 sec
        Start 203: driver.test_use_pch_msvc
203/205 Test #203: driver.test_use_pch_msvc ..........................   Passed    0.17 sec
        Start 204: fix_includes_test
204/205 Test #204: fix_includes_test .................................   Passed    0.25 sec
        Start 205: iwyu_tool_test
205/205 Test #205: iwyu_tool_test ....................................   Passed    0.80 sec

99% tests passed, 1 tests failed out of 205

Total Test time (real) =  52.06 sec

The following tests FAILED:
	198 - driver.test_offload_openmp (Failed)
Errors while running CTest
FAILED: CMakeFiles/test.util
```

Test https://github.com/include-what-you-use/include-what-you-use/blob/master/tests/driver/offload_openmp.c is failing. It looks like a failure of some sorts is expected, but the absence of a NVIDIA GPU seems to throw it off. `/usr/bin/nvptx-arch` doesn't return anything on host system.

Is there a way to make this test work or should I just remove the `tests/driver/offload_openmp.c` file?

**Comment by kimgr** [comment]
@meator I'm kind of glad to see this show up -- I've regretted adding that testcase :slightly_smiling_face: 

I recommend you just remove it, and I'll do the same on master.

**Comment by kimgr** [comment]
https://github.com/include-what-you-use/include-what-you-use/pull/1565

**Comment by kimgr** [comment]
Removed on master as of https://github.com/include-what-you-use/include-what-you-use/commit/92d9ad9721812224893deca39d934dff6bdb8587.

**Comment by meator** [comment]
Thanks!
