### ISSUE TITLE
driver.test_offload_apple fails on Exherbo Linux in IWYU 0.22

### ISSUE THREAD

**Issue by eternaleye** [include-what-you-use/include-what-you-use#1643]
Attempting to build and test IWYU 0.22 against Clang 18 on Exherbo Linux fails `driver.test_offload_apple` with the following:

```
197: >>> Running /var/tmp/paludis/build/dev-util-include-what-you-use-0.22/work/build/bin/include-what-you-use -Xiwyu --verbose=3 -target arm64-apple-macosx11.0.0 -x hip -nogpulib -nogpuinc tests/driver/offload_apple.c
197: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead
197: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead
197: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead
197: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead
197: warning: ignoring offload job for device toolchain: hip
197: 
197: (tests/driver/offload_apple.c has correct #includes/fwd-decls)
197: 
197: Traceback (most recent call last):
197:   File "/var/tmp/paludis/build/dev-util-include-what-you-use-0.22/work/include-what-you-use-0.22/run_iwyu_tests.py", line 161, in <module>
197:     exit(RunTestFile(runner_args.run_test_file))
197:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
197:   File "/var/tmp/paludis/build/dev-util-include-what-you-use-0.22/work/include-what-you-use-0.22/run_iwyu_tests.py", line 127, in RunTestFile
197:     TestIwyuOnRelevantFiles(cc_file)
197:   File "/var/tmp/paludis/build/dev-util-include-what-you-use-0.22/work/include-what-you-use-0.22/run_iwyu_tests.py", line 64, in TestIwyuOnRelevantFiles
197:     iwyu_test_util.TestIwyuOnRelativeFile(filename, files_to_check, verbose=True)
197:   File "/var/tmp/paludis/build/dev-util-include-what-you-use-0.22/work/include-what-you-use-0.22/iwyu_test_util.py", line 688, in TestIwyuOnRelativeFile
197:     raise AssertionError(''.join(failures))
197: AssertionError: 
197: Unexpected diagnostic:
197: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead
197: 
197: Unexpected diagnostic:
197: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead
197: 
197: Unexpected diagnostic:
197: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead
197: 
197: Unexpected diagnostic:
197: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead
197: 
197/204 Test #197: driver.test_offload_apple .........................***Failed    0.42 sec
```

I suspect the issue is that Exherbo, being a natively cross-compiled distribution, has clang set up to look for a target's include directory at `/usr/${target_triple}/include`, and the system is not set up such that the target `arm64-apple-macosx11.0.0` is populated. I'd expect that any system that's set up to be ready to cross-compile a (near-arbitrary) set of targets using the system compilers would fail similarly; this test likely should be restricted to machines where this target is actually viable to compile for.

**Comment by kimgr** [comment]
Our test framework has a `IWYU_REQUIRES: has-target(xyz)` construct to do target filtering, but now that I look at it, the supported targets only seem to be CPU arch targets (the output of `-print-targets`). Not sure if there's a switch to ask Clang/IWYU for all supported target _triples_...?

You can safely disable the test, it's only used to check that IWYU skips offload jobs if included on the command-line, and that's likely to work even if not exercised on the platform.

**Comment by kimgr** [comment]
@eternaleye 

The test seems to pass even without the triple -- could you see if this works in your environment?
```diff
From 7333789be80d61be22de6dad26beddb89f834d66 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Kim=20Gr=C3=A4sman?= <kim.grasman@gmail.com>
Date: Mon, 6 Jan 2025 16:41:44 +0100
Subject: [PATCH] Remove apple target triple from offload test

---
 tests/driver/offload_apple.c | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/tests/driver/offload_apple.c b/tests/driver/offload_apple.c
index 09df895..dd54e84 100644
--- a/tests/driver/offload_apple.c
+++ b/tests/driver/offload_apple.c
@@ -10,7 +10,7 @@
 // Check that IWYU ignores the extra offload compiler job produced when
 // compiling for Apple's HIP.
 
-// IWYU_ARGS: -target arm64-apple-macosx11.0.0 -x hip -nogpulib -nogpuinc
+// IWYU_ARGS: -x hip -nogpulib -nogpuinc
 
 // IWYU~: ignoring offload job for device toolchain: hip
 
-- 
2.43.0
```
