### ISSUE TITLE
About use question

### ISSUE THREAD

**Issue by Reishu** [include-what-you-use/include-what-you-use#619]
Hello
I have a visual studio solution with projects, which use msvs compiler
I used sourcetrail for make compilation_database.json from solution

But iwyu_tool.py -p="path to json" doesn't work with error What is wrong?

`  File "F:\iwyu\include-what-you-use\iwyu_tool.py", line 343, in <module>
    _bootstrap()
  File "F:\iwyu\include-what-you-use\iwyu_tool.py", line 339, in _bootstrap
    FORMATTERS[args.output_format], args.jobs, iwyu_args))
  File "F:\iwyu\include-what-you-use\iwyu_tool.py", line 276, in main
    return execute(invocations, verbose, formatter, jobs)
  File "F:\iwyu\include-what-you-use\iwyu_tool.py", line 239, in execute
    print(formatter(invocation.start(verbose).get_output()))
  File "F:\iwyu\include-what-you-use\iwyu_tool.py", line 191, in start
    return Process.start(self)
  File "F:\iwyu\include-what-you-use\iwyu_tool.py", line 151, in start
    stderr=subprocess.STDOUT)
  File "\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 929, in _execute_child
    args = list2cmdline(args)
  File "\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 441, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'NoneType' is not iterable`

i want get a file log about all files

**Comment by kimgr** [comment]
Can you show an excerpt from the generated `compilation_database.json`? It sounds like we're looking for an argument that isn't there.

**Comment by Reishu** [comment]
Rename extension to json
[compilation_database.txt](https://github.com/include-what-you-use/include-what-you-use/files/2661810/compilation_database.txt)

**Comment by Reishu** [comment]
P.S. with another project i get another error 
I try use utf-8, utf-8-sig encodings

Traceback (most recent call last):
  File "D:\include-what-you-use\bin\iwyu_tool.py", line 222, in <module>
    _bootstrap()
  File "D:\include-what-you-use\bin\iwyu_tool.py", line 218, in _bootstrap
    FORMATTERS[args.output_format], iwyu_args))
  File "D:\include-what-you-use\bin\iwyu_tool.py", line 158, in main
    run_iwyu(cwd, compile_command, iwyu_args, verbose, formatter)
  File "D:\include-what-you-use\bin\iwyu_tool.py", line 114, in run_iwyu
    formatter(get_output(cwd, command))
  File "D:\include-what-you-use\bin\iwyu_tool.py", line 95, in get_output
    return process.communicate()[0].decode("utf-8").splitlines()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xad in position 23: invalid start byte

**Comment by kimgr** [comment]
I can't reproduce any problems with the posted `compilation_database.txt`. It just seems to work fine.

**Comment by Reishu** [comment]
Yes,
But files encdong is utf-8 (or utf-8-sig, i try both )
It's problem?

**Comment by kimgr** [comment]
There is no file -- 

> return process.communicate()[0].decode("utf-8").splitlines()

This happens when decoding the output from the `include-what-you-use` executable. And the only non-ASCII output it prints would come from your source code or file names.

**Comment by kimgr** [comment]
Ah, I see what you're saying now. You're on Windows, right? I wonder if the console subsystem re-codes the output to something else. It's been years since I used Windows, but there used to be a concept of a System Code Page -- which I think is the multibyte encoding used by the console (among other things). Could you find that in your "Regional Settings" and see if it's something other than UTF-8? I'm not sure I can safely recommend you to change it, but it might give an idea of what the output encoding is.

**Comment by Reishu** [comment]
Yes, Windows 10
I'm going to try and write about the results, tomorrow 
Thank you

**Comment by Reishu** [comment]
Succesfully change codepage in command line
It's work! Great!

**Comment by kimgr** [comment]
Good to hear!

Maybe `iwyu_tool.py` just shouldn't decode in the first place. It's convenient to have the output as a string, but most string operations (including regular expressions) are also available for bytes in Python, so maybe that's a way to eliminate the problem altogether. Will need to experiment.

**Comment by Reishu** [comment]
`iwyu_tool.py` work good for manual review of changes

Next, I try to change with `fix_includes.py.`
`iwyu_tool.py` logged file has utf-8 encoding

Whan can I fix this?
Try to change encoding - it's doesn't work

```
(skipping D:/Paint/PaintApp/PaintApp/view/draw/PaintersCreator.h: iwyu reports no contentful changes)
(skipping D:/Paint/PaintApp/PaintApp/model/tempModels/ModelFilter.h: iwyu reports no contentful changes)
(skipping D:/Paint/PaintApp/PaintApp/model/tempModels/TmpModel.h: iwyu reports no contentful changes)
(skipping D:/Paint/PaintApp/PaintApp/model/tempModels/TmpModelCreateFigure.h: iwyu reports no contentful changes)
(skipping D:/Paint/PaintApp/PaintApp/stdafx.cpp: iwyu reports no contentful changes)
Traceback (most recent call last):
  File "D:\include-what-you-use\bin\fix_includes.py", line 2394, in <module>
    num_files_fixed = main(sys.argv)
  File "D:\include-what-you-use\bin\fix_includes.py", line 2390, in main
    return ProcessIWYUOutput(sys.stdin, files_to_modify, flags)
  File "D:\include-what-you-use\bin\fix_includes.py", line 2258, in ProcessIWYUOutput
    return FixManyFiles(contentful_records, flags)
  File "D:\include-what-you-use\bin\fix_includes.py", line 2159, in FixManyFiles
    fixed_lines = GetFixedFile(iwyu_record, flags)
  File "D:\include-what-you-use\bin\fix_includes.py", line 2053, in GetFixedFile
    flags.dry_run or flags.checkout_command)
  File "D:\include-what-you-use\bin\fix_includes.py", line 540, in _ReadWriteableFile
    return _ReadFile(filename)
  File "D:\include-what-you-use\bin\fix_includes.py", line 516, in _ReadFile
    return open(filename).read().splitlines()
  File "C:\Users\Surkov\AppData\Local\Programs\Python\Python35\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 741: character maps to <undefined>
```

**Comment by kimgr** [comment]
You're running a fairly old version of IWYU, judging from the source hints in the traceback. Can you try pulling out the latest scripts from master? Newer `fix_includes.py` should handle encodings better.

**Comment by Reishu** [comment]
Thank you, newest version works fine
close issue

P.S. I used include-what-you-use 0.7 (aka Clang+LLVM 3.9) (30 October 2016) from download, because I I needed exe file.
