### ISSUE TITLE
How to use IWYU on Windows with UE4 project?

### ISSUE THREAD

**Issue by Takao-7** [include-what-you-use/include-what-you-use#749]
We found a major "include cascade issue" in our game project, which I want to fix now.
We currently have 460 cpp files and I think the majority of them had header files indirectly included through our [GameProjectName].h file which is included in every cpp file. So fixing them all manually is not really an option.

This command:
`make -k CXX=/path/to/llvm/Debug+Asserts/bin/include-what-you-use 2> /tmp/iwyu.out`
simply does not work. I have altered it to this:
`cmake -k CXX="C:\Users\Paul\Software\IWYU\build\bin\Release\include-what-you-use.exe" \tmp\iwyu.out`
But I get the error "CMake Error: The source directory "/tmp/iwyu.out" does not exist.".
I assume that `iqyu.out` should be an output file, but even when I create a folder iwyu.out I get the same error.
Changing from / to \ also does not fix anything.
I'm running the command from the main folder where the .sln file is located.

**Comment by kimgr** [comment]
Is this a cmake project, or do you only have Visual Studio project files for building?

**Comment by Takao-7** [comment]
Only Visual Studio, however
I think Unreal Engine uses some other tools for building.

**Comment by kimgr** [comment]
Maybe you can use this tool to export a json compilation database: https://www.sourcetrail.com/blog/export_clang_compilation_database_from_visual_studio_solution/

And then use iwyu_tool.py to use the compilation database with include-what-you-use.

**Comment by Takao-7** [comment]
I have used the tool and it generated a file with around 500 entries, which is the corect amount.

I then used `python "C:\Users\Paul\Software\IWYU\fix_includes.py" < compile_commands.json` both when in the main folder with the .sln file and in the main source folder, but I get the message

> IWYU edited 0 files on your behalf

**Comment by Takao-7** [comment]
I have created the compilation database and it contains around 500 entries, so it looks correct.

When I run this command from the main project folder (where the .sln file is located), I get an error:
`python "C:\Users\Paul\Software\IWYU\iwyu_tool.py" -p compile_commands.json`

```
Traceback (most recent call last):
  File "C:\Users\Paul\Software\IWYU\iwyu_tool.py", line 457, in <module>
    sys.exit(_bootstrap(sys.argv))
  File "C:\Users\Paul\Software\IWYU\iwyu_tool.py", line 452, in _bootstrap
    return main(args.dbpath, args.source, args.verbose,
  File "C:\Users\Paul\Software\IWYU\iwyu_tool.py", line 394, in main
    return execute(invocations, verbose, formatter, jobs)
  File "C:\Users\Paul\Software\IWYU\iwyu_tool.py", line 349, in execute
    print(formatter(invocation.start(verbose).get_output()))
  File "C:\Users\Paul\Software\IWYU\iwyu_tool.py", line 305, in start
    return Process.start(self)
  File "C:\Users\Paul\Software\IWYU\iwyu_tool.py", line 262, in start
    process = subprocess.Popen(
  File "C:\Users\Paul\Software\Python3_8\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Paul\Software\Python3_8\lib\subprocess.py", line 1247, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\Paul\Software\Python3_8\lib\subprocess.py", line 549, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Users\Paul\Software\Python3_8\lib\os.py", line 816, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

The compile_commands.json file is located in the main project folder.

**Comment by kimgr** [comment]
It looks like the `include-what-you-use` binary it's trying to launch is `None`.

This indicates that no matching binary was found either next to `iwyu_tool.py` or on the system `PATH`. Where's your `include-what-you-use.exe`?
