### ISSUE TITLE
False "incomplete type" compile errors

### ISSUE THREAD

**Issue by shivanshu3** [include-what-you-use/include-what-you-use#755]
We have similar code like the example I have below where Clang is able to compile it just fine without any errors or warnings, but IWYU isn't happy with it. It emits many compile errors, and therefore doesn't run the analysis on such files.

Why is this happening? Shouldn't all code that compiles with Clang, be able to work with IWYU? Note that I tried compiling this in MSVC as well, and it's happy with it too.

I ran clang-check on this file, and it doesn't complain about it either.

Contents of `main.cpp`:
```c++
#include <vector>

struct Foo;

struct Bar
{
   std::vector<Foo> foos;
};
```

Errors:
```
$>include-what-you-use.exe main.cpp -I"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include"
In file included from main.cpp:1:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\vector:6:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\xmemory:6:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\xmemory0:9:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\new:6:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\exception:8:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\type_traits:1010:19: error: incomplete type 'Foo' used in type trait expression
                : bool_constant<__is_trivially_destructible(_Ty)>
                                ^
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\type_traits:74:18: note: in instantiation of template class 'std::is_trivially_destructible<Foo>' requested here
                : _Conjunction<_First::value, _First, _Rest...>::type
                               ^
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\type_traits:80:45: note: in instantiation of template class 'std::conjunction<std::is_trivially_destructible<Foo>,
      std::disjunction<std::_Is_default_allocator<std::allocator<Foo>, void>, std::_Has_no_alloc_destroy<std::allocator<Foo>, Foo *, void> > >' requested here
        _INLINE_VAR constexpr bool conjunction_v = conjunction<_Traits...>::value;
                                                   ^
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\xmemory0:1158:52: note: in instantiation of variable template specialization 'std::conjunction_v<std::is_trivially_destructible<Foo>,
      std::disjunction<std::_Is_default_allocator<std::allocator<Foo>, void>, std::_Has_no_alloc_destroy<std::allocator<Foo>, Foo *, void> > >' requested here
        _Destroy_range1(_First, _Last, _Al, bool_constant<conjunction_v<
                                                          ^
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\vector:1849:3: note: in instantiation of function template specialization 'std::_Destroy_range<std::allocator<Foo> >' requested here
                _Destroy_range(_First, _Last, this->_Getal());
                ^
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\vector:1915:4: note: in instantiation of member function 'std::vector<Foo, std::allocator<Foo> >::_Destroy' requested here
                        _Destroy(this->_Myfirst(), this->_Mylast());
                        ^
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\vector:894:3: note: in instantiation of member function 'std::vector<Foo, std::allocator<Foo> >::_Tidy' requested here
                _Tidy();
                ^
main.cpp:5:8: note: in instantiation of member function 'std::vector<Foo, std::allocator<Foo> >::~vector' requested here
struct Bar
       ^
main.cpp:3:8: note: forward declaration of 'Foo'
struct Foo;
       ^

<More similar errors ...>
```

IWYU version: 0.13

**Comment by shivanshu3** [comment]
I ran it under a debugger, and looks like this might actually be by design? The method `InstantiateImplicitMethods` causes implicit ctor, dtor, etc to be instantiated, which causes the compile errors in this case.

Would it be possible to add a command line flag to disable this behavior?

**Comment by kimgr** [comment]
Thanks for digging out the root cause!

That part is actually required for complete iwyu analysis, if I remember correctly. The reasoning is that `Bar` should be self-sufficient - including its header should give you enough to create an instance of it, or something to that effect.

I see this example has a forward decl for Foo, which could serve as a signal that the responsibility belongs with users of Bar, but we don't handle it like that yet.

**Comment by NickNick** [comment]
@shivanshu3 I think if you define the Bar::~Bar out of line, this may compile (like with std::unique_ptr). Without that, it's generating the default one inline, which will need to know how big a Foo is.

**Comment by shivanshu3** [comment]
@kimgr, would you consider a PR where I add a command line option to disable this behavior? Something simple like checking for a bool inside `InstantiateImplicitMethods` and returning without doing anything.

**Comment by kimgr** [comment]
@shivanshu3 Have you tried it? What are the effects in general? I would love to get rid of that code in general, but it seems pretty central to me. As I understand it, it mostly exists to synthesize uses of member constructors and destructors. But I could be missing something.

**Comment by shivanshu3** [comment]
@kimgr yeah, I've been using it for a few months and it's working well. Without this change, it causes compile errors in hundreds of our files and fixing all those breaks isn't really feasible.

**Comment by kimgr** [comment]
But I don't understand why `InstantiateImplicitMethods` is even necessary, in that case... You must see some difference in behavior...?

**Comment by shivanshu3** [comment]
@kimgr  There was no difference in behavior in the test output. I ran the test suite before my change and after my change, and the test output was pretty much the same. A couple lines were just reordered in the log. I've attached the logs before and after my change. This is the change I made:

```diff
[before.txt](https://github.com/include-what-you-use/include-what-you-use/files/4637246/before.txt)
[after.txt](https://github.com/include-what-you-use/include-what-you-use/files/4637247/after.txt)


diff --git a/iwyu.cc b/iwyu.cc
index 37c7e99..24214f8 100644
--- a/iwyu.cc
+++ b/iwyu.cc
@@ -617,6 +617,7 @@ class BaseAstVisitor : public RecursiveASTVisitor<Derived> {
   // decl.  We're hoping it will always be safe to modify the AST
   // while it's being traversed!
   void InstantiateImplicitMethods(CXXRecordDecl* decl) {
+    return;
     if (decl->isDependentType())   // only instantiate if class is instantiated
       return;
```

**Comment by kimgr** [comment]
Aah, you're running on Windows. When I remove all calls to `InstantiateImplicitMethods`, I see a new test failure:
```
.
======================================================================
FAIL: runTest (__main__.badinc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./run_iwyu_tests.py", line 279, in <lambda>
    {'runTest': lambda self, f=filename: self.RunOneTest(f),
  File "./run_iwyu_tests.py", line 250, in RunOneTest
    iwyu_flags, clang_flags, verbose=True)
  File "/home/kgrasman/code/iwyu/include-what-you-use/iwyu_test_util.py", line 455, in TestIwyuOnRelativeFile
    test_case.assertTrue(not failures, ''.join(failures))
AssertionError: 
tests/cxx/badinc.cc:278: Unmatched regex:
I1_Class is...*badinc-i1.h

tests/cxx/badinc.cc:435: Unmatched regex:
I1_Class is...*badinc-i1.h


----------------------------------------------------------------------
Ran 131 tests in 10.868s

FAILED (failures=1)
```

I wish the tests were more platform agnostic, but there are obvious difficulties with standard library differences. We try to make new tests independent of the standard library, but the lion's share of the tests predate that decision (or require the standard library because they test interaction between the language and the stdlib).

Anyway, to the actual problem. badinc.cc:278 is this block:
```
// This template struct is never instantiated, and neither is the
// struct that includes it as a member.  Even so, we should call its
// methods to be instantiated for our testing, so we notice the
// requirement for I1_Class's full type (via the default constructor).
template<class T> struct NeverCalledTemplateStruct {
  NeverCalledTemplateStruct() { T t; }
};
// IWYU: I1_Class is...*badinc-i1.h
struct NeverCalledStruct {
  // IWYU: I1_Class needs a declaration
  NeverCalledTemplateStruct<I1_Class> c;
};
```
I think I agree with that test's analysis that the construction of `c` should require the full type of `I1_Class`

But it's interesting with the "NeverCalled" quality -- I think this means there's a difference in expectations between MSVC users and GCC users. MSVC code bases are primarily in the "late-parsed template" camp, and portable GCC-friendly code bases usually aren't.

So... I wonder what would happen if we hide `InstantiateImplicitMethods` behind the `-fdelayed-template-parsing` flag? That is, don't do it if delayed template parsing is enabled... I suspect you're already using that flag one way or another to get IWYU's clang-based parser to accept the MSVC standard library.

**Comment by kimgr** [comment]
See here for existing use of that flag (in an assertion): https://github.com/include-what-you-use/include-what-you-use/blob/master/iwyu.cc#L3686.

**Comment by kimgr** [comment]
Hmm. When googling for info about delayed template parsing vs two-phase lookup, I landed in an old IWYU bug: https://github.com/include-what-you-use/include-what-you-use/issues/129. There's quite a lot of good reasoning there, that I think led up to `ParseFunctionTemplates`. One thing I mentioned in passing was that maybe we should treat `InstantiateImplicitMethods` the same as delayed template parsing, so that we run it as a separate pass after IWYU is done.

If you want to experiment with these ideas, I'd be most grateful -- I don't have a Windows rig to run on anymore.
