### ISSUE TITLE
segmentation fault in include-what-you-use with trivial code

### ISSUE THREAD

**Issue by alexezeder** [include-what-you-use/include-what-you-use#820]
I tried to run include-what-you-use for some project with CMake (`-DCMAKE_CXX_INCLUDE_WHAT_YOU_USE="<path_to_bin>"`) and it kept failing with segfault in one of cpp files. Other files didn't produce any error, except for `Cycle in include-mapping: <gst/gststreamcollection.h> -> <gst/gststreamcollection.h>`, but I just hardcode it in `iwyu_include_picker.cc`, cause I didn't realize how to use mapping in this case, if it is even possible to use mapping for that. Back to this file that _segfaults_ include-what-you-use, I minimized it as much as I can (keeping it segfaulting), here it is:
```cpp
#include <map>
#include <vector>

class ValueType
{
public:
    explicit ValueType()
        : m_vectorField()
    {}

private:
    std::vector<int> m_vectorField;
};

void function()
{
    std::map<int, ValueType> someMap;
    someMap[1] = ValueType();
}
```
```
cmake --build .../iwyuTest/cmake-build-debug-clang-9 --target iwyuTest -- -j 12
[ 33%] Building CXX object CMakeFiles/iwyuTest.dir/test.cpp.o
Error running '.../include-what-you-use/build/bin/include-what-you-use': Segmentation fault
```

How can this segfault be fixed?
- by using `.at()` instead of `[]`
```cpp
someMap.at(1) = ValueType();
```
- by using `int` field in `ValueType`
```cpp
class ValueType
{
public:
    explicit ValueType()
        : m_intField()
    {}

private:
    int m_intField;
};
```
- by removing `explicit` from constructor of `ValueType`
```cpp
ValueType()
    : m_vectorField()
{}
```
- and probably by fixing it in include-what-you-use.

I tried to build include-what-you-use binary from clang_7.0 branch with gcc-9, from clang_9.0 branch with clang-9 and gcc-9, but segfault didn't disappear.

Unfortunately, I cannot check this code with clang_10 branch, but if it's fixed in this branch (or master) then maybe it should be backported to older ones if it's possible. Maybe it doesn't work only on my machine, so please test this code on yours.

**Comment by kimgr** [comment]
Thanks for the repro! This is a long-standing bug where Clang crashes when driven from IWYU, and I haven't found a way to fix it yet. Related reports: https://github.com/include-what-you-use/include-what-you-use/issues/419 and https://github.com/include-what-you-use/include-what-you-use/issues/601.

The #601 one is my favorite, because it's entirely freestanding and doesn't need an exact version of toolchains/standard libraries/third-party code. But it's also completely unintelligible, so this is a nice complement.

**Comment by kimgr** [comment]
Oh yeah, to "prove" it's the same issue, the backtrace is:
```
#0  0x00005555565ca479 in clang::Sema::PushOnScopeChains(clang::NamedDecl*, clang::Scope*, bool) ()
#1  0x00005555565cceb5 in clang::Sema::LazilyCreateBuiltin(clang::IdentifierInfo*, unsigned int, clang::Scope*, bool, clang::SourceLocation) ()
#2  0x000055555623d244 in clang::Sema::LookupBuiltin(clang::LookupResult&) ()
#3  0x0000555556248683 in clang::Sema::LookupName(clang::LookupResult&, clang::Scope*, bool) ()
#4  0x00005555560bbbe0 in clang::Sema::ActOnIdExpression(clang::Scope*, clang::CXXScopeSpec&, clang::SourceLocation, clang::UnqualifiedId&, bool, bool, clang::CorrectionCandidateCallback*, bool, clang::Token*) ()
#5  0x00005555560bb78e in clang::Sema::DefaultVariadicArgumentPromotion(clang::Expr*, clang::Sema::VariadicCallType, clang::FunctionDecl*) ()
#6  0x00005555560d7258 in clang::Sema::GatherArgumentsForCall(clang::SourceLocation, clang::FunctionDecl*, clang::FunctionProtoType const*, unsigned int, llvm::ArrayRef<clang::Expr*>, llvm::SmallVectorImpl<clang::Expr*>&, clang::Sema::VariadicCallType, bool, bool) ()
#7  0x00005555560d555d in clang::Sema::ConvertArgumentsForCall(clang::CallExpr*, clang::Expr*, clang::FunctionDecl*, clang::FunctionProtoType const*, llvm::ArrayRef<clang::Expr*>, clang::SourceLocation, bool) ()
#8  0x00005555560d8950 in clang::Sema::BuildResolvedCallExpr(clang::Expr*, clang::NamedDecl*, clang::SourceLocation, llvm::ArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, clang::CallExpr::ADLCallKind) ()
#9  0x0000555556323035 in FinishOverloadedCallExpr(clang::Sema&, clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, clang::OverloadCandidateSet*, clang::OverloadCandidate**, clang::OverloadingResult, bool) ()
#10 0x000055555632267c in clang::Sema::BuildOverloadedCallExpr(clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) ()
#11 0x00005555560bcb8b in clang::Sema::BuildCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool) ()
#12 0x00005555560d7b94 in clang::Sema::ActOnCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*) ()
#13 0x0000555556454c1c in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCallExpr(clang::CallExpr*) ()
#14 0x0000555556441e6f in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformType(clang::TypeLocBuilder&, clang::TypeLoc) ()
#15 0x00005555564418d2 in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformType(clang::TypeSourceInfo*) ()
#16 0x0000555556441609 in clang::Sema::SubstType(clang::TypeSourceInfo*, clang::MultiLevelTemplateArgumentList const&, clang::SourceLocation, clang::DeclarationName, bool) ()
#17 0x00005555564747d3 in clang::TemplateDeclInstantiator::InstantiateTypedefNameDecl(clang::TypedefNameDecl*, bool) ()
#18 0x0000555556475cee in clang::TemplateDeclInstantiator::VisitTypedefDecl(clang::TypedefDecl*) ()
#19 0x000055555644a0c3 in clang::Sema::InstantiateClass(clang::SourceLocation, clang::CXXRecordDecl*, clang::CXXRecordDecl*, clang::MultiLevelTemplateArgumentList const&, clang::TemplateSpecializationKind, bool) ()
#20 0x000055555644bdf4 in clang::Sema::InstantiateClassTemplateSpecialization(clang::SourceLocation, clang::ClassTemplateSpecializationDecl*, clang::TemplateSpecializationKind, bool) ()
#21 0x00005555564ccf7e in void llvm::function_ref<void ()>::callback_fn<clang::Sema::RequireCompleteTypeImpl(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser*)::$_3>(long) ()
#22 0x00005555564f9f0b in clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) ()
#23 0x00005555564bc7ea in clang::Sema::RequireCompleteTypeImpl(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser*) ()
#24 0x00005555564bbe8f in clang::Sema::RequireCompleteType(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser&) ()
#25 0x00005555565587b3 in clang::Sema::RequireCompleteDeclContext(clang::CXXScopeSpec&, clang::DeclContext*) ()
#26 0x00005555563a1670 in clang::Sema::CheckTypenameType(clang::ElaboratedTypeKeyword, clang::SourceLocation, clang::NestedNameSpecifierLoc, clang::IdentifierInfo const&, clang::SourceLocation, bool) ()
#27 0x000055555646384b in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformDependentNameType(clang::TypeLocBuilder&, clang::DependentNameTypeLoc, bool) ()
#28 0x00005555564418d2 in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformType(clang::TypeSourceInfo*) ()
#29 0x000055555644975d in clang::Sema::SubstBaseSpecifiers(clang::CXXRecordDecl*, clang::CXXRecordDecl*, clang::MultiLevelTemplateArgumentList const&) ()
#30 0x0000555556449f5b in clang::Sema::InstantiateClass(clang::SourceLocation, clang::CXXRecordDecl*, clang::CXXRecordDecl*, clang::MultiLevelTemplateArgumentList const&, clang::TemplateSpecializationKind, bool) ()
#31 0x000055555644bdf4 in clang::Sema::InstantiateClassTemplateSpecialization(clang::SourceLocation, clang::ClassTemplateSpecializationDecl*, clang::TemplateSpecializationKind, bool) ()
#32 0x00005555564ccf7e in void llvm::function_ref<void ()>::callback_fn<clang::Sema::RequireCompleteTypeImpl(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser*)::$_3>(long) ()
#33 0x00005555564f9f0b in clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) ()
#34 0x00005555564bc7ea in clang::Sema::RequireCompleteTypeImpl(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser*) ()
#35 0x00005555564bbe8f in clang::Sema::RequireCompleteType(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser&) ()
#36 0x0000555556020097 in clang::Sema::CheckBaseSpecifier(clang::CXXRecordDecl*, clang::SourceRange, bool, clang::AccessSpecifier, clang::TypeSourceInfo*, clang::SourceLocation) ()
#37 0x0000555556449a3a in clang::Sema::SubstBaseSpecifiers(clang::CXXRecordDecl*, clang::CXXRecordDecl*, clang::MultiLevelTemplateArgumentList const&) ()
#38 0x0000555556449f5b in clang::Sema::InstantiateClass(clang::SourceLocation, clang::CXXRecordDecl*, clang::CXXRecordDecl*, clang::MultiLevelTemplateArgumentList const&, clang::TemplateSpecializationKind, bool) ()
#39 0x000055555644bdf4 in clang::Sema::InstantiateClassTemplateSpecialization(clang::SourceLocation, clang::ClassTemplateSpecializationDecl*, clang::TemplateSpecializationKind, bool) ()
#40 0x00005555564ccf7e in void llvm::function_ref<void ()>::callback_fn<clang::Sema::RequireCompleteTypeImpl(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser*)::$_3>(long) ()
#41 0x00005555564f9f0b in clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) ()
#42 0x00005555564bc7ea in clang::Sema::RequireCompleteTypeImpl(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser*) ()
#43 0x00005555564bbe8f in clang::Sema::RequireCompleteType(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser&) ()
#44 0x0000555556020097 in clang::Sema::CheckBaseSpecifier(clang::CXXRecordDecl*, clang::SourceRange, bool, clang::AccessSpecifier, clang::TypeSourceInfo*, clang::SourceLocation) ()
#45 0x0000555556449a3a in clang::Sema::SubstBaseSpecifiers(clang::CXXRecordDecl*, clang::CXXRecordDecl*, clang::MultiLevelTemplateArgumentList const&) ()
#46 0x0000555556449f5b in clang::Sema::InstantiateClass(clang::SourceLocation, clang::CXXRecordDecl*, clang::CXXRecordDecl*, clang::MultiLevelTemplateArgumentList const&, clang::TemplateSpecializationKind, bool) ()
#47 0x000055555644bdf4 in clang::Sema::InstantiateClassTemplateSpecialization(clang::SourceLocation, clang::ClassTemplateSpecializationDecl*, clang::TemplateSpecializationKind, bool) ()
#48 0x00005555564ccf7e in void llvm::function_ref<void ()>::callback_fn<clang::Sema::RequireCompleteTypeImpl(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser*)::$_3>(long) ()
#49 0x00005555564f9f0b in clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) ()
#50 0x00005555564bc7ea in clang::Sema::RequireCompleteTypeImpl(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser*) ()
#51 0x00005555564bbe8f in clang::Sema::RequireCompleteType(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser&) ()
#52 0x0000555556020097 in clang::Sema::CheckBaseSpecifier(clang::CXXRecordDecl*, clang::SourceRange, bool, clang::AccessSpecifier, clang::TypeSourceInfo*, clang::SourceLocation) ()
#53 0x0000555556449a3a in clang::Sema::SubstBaseSpecifiers(clang::CXXRecordDecl*, clang::CXXRecordDecl*, clang::MultiLevelTemplateArgumentList const&) ()
#54 0x0000555556449f5b in clang::Sema::InstantiateClass(clang::SourceLocation, clang::CXXRecordDecl*, clang::CXXRecordDecl*, clang::MultiLevelTemplateArgumentList const&, clang::TemplateSpecializationKind, bool) ()
#55 0x000055555644bdf4 in clang::Sema::InstantiateClassTemplateSpecialization(clang::SourceLocation, clang::ClassTemplateSpecializationDecl*, clang::TemplateSpecializationKind, bool) ()
#56 0x00005555564ccf7e in void llvm::function_ref<void ()>::callback_fn<clang::Sema::RequireCompleteTypeImpl(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser*)::$_3>(long) ()
#57 0x00005555564f9f0b in clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) ()
#58 0x00005555564bc7ea in clang::Sema::RequireCompleteTypeImpl(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser*) ()
#59 0x00005555564bbe8f in clang::Sema::RequireCompleteType(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser&) ()
#60 0x00005555565587b3 in clang::Sema::RequireCompleteDeclContext(clang::CXXScopeSpec&, clang::DeclContext*) ()
#61 0x00005555560c3b4a in clang::Sema::BuildQualifiedDeclarationNameExpr(clang::CXXScopeSpec&, clang::DeclarationNameInfo const&, bool, clang::Scope const*, clang::TypeSourceInfo**) ()
#62 0x000055555645e3c3 in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformDependentScopeDeclRefExpr(clang::DependentScopeDeclRefExpr*, bool, clang::TypeSourceInfo**) ()
#63 0x000055555645d432 in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformTemplateArgument(clang::TemplateArgumentLoc const&, clang::TemplateArgumentLoc&, bool) ()
#64 0x000055555645b9e2 in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformTemplateSpecializationType(clang::TypeLocBuilder&, clang::TemplateSpecializationTypeLoc, clang::TemplateName) ()
#65 0x000055555645b27e in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformTSIInObjectScope(clang::TypeLoc, clang::QualType, clang::NamedDecl*, clang::CXXScopeSpec&) ()
#66 0x000055555644f788 in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformNestedNameSpecifierLoc(clang::NestedNameSpecifierLoc, clang::QualType, clang::NamedDecl*) ()
#67 0x00005555564637a7 in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformDependentNameType(clang::TypeLocBuilder&, clang::DependentNameTypeLoc, bool) ()
#68 0x00005555564418d2 in clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformType(clang::TypeSourceInfo*) ()
#69 0x0000555556445b14 in clang::Sema::SubstType(clang::QualType, clang::MultiLevelTemplateArgumentList const&, clang::SourceLocation, clang::DeclarationName) ()
#70 0x0000555556390ee9 in clang::Sema::CheckTemplateArgument(clang::NamedDecl*, clang::TemplateArgumentLoc&, clang::NamedDecl*, clang::SourceLocation, clang::SourceLocation, unsigned int, llvm::SmallVectorImpl<clang::TemplateArgument>&, clang::Sema::CheckTemplateArgumentKind) ()
#71 0x00005555563fbb87 in clang::Sema::FinishTemplateArgumentDeduction(clang::FunctionTemplateDecl*, llvm::SmallVectorImpl<clang::DeducedTemplateArgument>&, unsigned int, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, llvm::SmallVectorImpl<clang::Sema::OriginalCallArg> const*, bool, llvm::function_ref<bool ()>) ()
#72 0x00005555563fd5bc in clang::Sema::DeduceTemplateArguments(clang::FunctionTemplateDecl*, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::FunctionDecl*&, clang::sema::TemplateDeductionInfo&, bool, llvm::function_ref<bool (llvm::ArrayRef<clang::QualType>)>) ()
#73 0x000055555630f23c in clang::Sema::AddTemplateOverloadCandidate(clang::FunctionTemplateDecl*, clang::DeclAccessPair, clang::TemplateArgumentListInfo*, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool, bool, bool, clang::CallExpr::ADLCallKind, clang::OverloadCandidateParamOrder) ()
#74 0x000055555624c153 in clang::Sema::LookupSpecialMember(clang::CXXRecordDecl*, clang::Sema::CXXSpecialMember, bool, bool, bool, bool, bool) ()
#75 0x000055555606edc7 in (anonymous namespace)::SpecialMemberDeletionInfo::shouldDeleteForClassSubobject(clang::CXXRecordDecl*, llvm::PointerUnion<clang::CXXBaseSpecifier*, clang::FieldDecl*>, unsigned int) ()
#76 0x0000555556037f55 in clang::Sema::ShouldDeleteSpecialMember(clang::CXXMethodDecl*, clang::Sema::CXXSpecialMember, clang::Sema::InheritedConstructorInfo*, bool) ()
#77 0x000055555603da7a in clang::Sema::DeclareImplicitDefaultConstructor(clang::CXXRecordDecl*) ()
#78 0x000055555625d7b1 in void llvm::function_ref<void ()>::callback_fn<clang::Sema::LookupConstructors(clang::CXXRecordDecl*)::$_13>(long) ()
#79 0x00005555564f9f0b in clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) ()
#80 0x000055555624c47e in clang::Sema::LookupConstructors(clang::CXXRecordDecl*) ()
#81 0x0000555555a47a2f in include_what_you_use::BaseAstVisitor<include_what_you_use::InstantiatedTemplateVisitor>::InstantiateImplicitMethods(clang::CXXRecordDecl*) ()
#82 0x00005555559dc286 in include_what_you_use::BaseAstVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseCXXRecordDecl(clang::CXXRecordDecl*) ()
#83 0x00005555559af521 in clang::RecursiveASTVisitor<include_what_you_use::InstantiatedTemplateVisitor>::TraverseDecl(clang::Decl*) ()
...
```

**Comment by kimgr** [comment]
Fix merged to main, closing.

**Comment by alexezeder** [comment]
Nice, thank you! 👍

The combination of two problems in the first post actually made me stop integrating IWYU everywhere, but now I'm ready to test it again.
